FROM keymetrics/pm2:18-alpine

LABEL maintainer="jaime.ziga@gmail.com"

# Install app dependencies
# ENV NPM_CONFIG_LOGLEVEL warn
# RUN npm install

# Show current folder structure in logs
RUN ls -al -R
